/** Compatibility facade over `@/lib/public-copy` (Copy SoT). Prefer public-copy for new code. */

import { brand as publicBrand, copy as pc } from "./public-copy";

export const BRAND = publicBrand.name;
export const BRAND_SEP = publicBrand.sep;

/** @deprecated Prefer pack keys from `@/lib/public-copy`. */
export const copy = {
  home: {
    metaTitle: pc.home.meta_title,
    metaDescription: pc.home.meta_description,
    claim: pc.home.claim,
    helper: pc.home.helper,
    labelQuery: pc.home.label_query,
    labelPlace: pc.home.label_place,
    placeholderQuery: pc.home.placeholder_query,
    placeholderPlace: pc.home.placeholder_place,
    ctaSearch: pc.home.cta_search,
    ctaEmployers: pc.home.cta_employers,
    sectionLatest: pc.home.section_latest,
    fact1Title: "Mzda na první pohled",
    fact1Body: "Každá nabídka ukazuje odměnu, nebo upřímné Neuvedeno.",
    fact2Title: "Firma přes IČO",
    fact2Body: "Údaje z registru. Víte, kdo inzeruje.",
    fact3Title: "Jedno hledání",
    fact3Body: "Klíčové slovo a lokalita. Filtry v draweru, ne polovina obrazovky.",
    hubPoradna: pc.chrome.nav_poradna,
    hubPoradnaBody: "Jak vyjednat mzdu, změnit obor, nebo se připravit na pohovor.",
    hubKurzy: pc.chrome.nav_kurzy,
    hubKurzyBody: "Rekvalifikace a kurzy podle oboru. Online i prezenční.",
    hubNastroje: pc.chrome.nav_nastroje,
    hubNastrojeBody: "Čistá mzda, srovnání platů, checklist pohovoru. Bez účtu.",
    employerTitle: pc.proFirmy.claim,
    employerBody: pc.proFirmy.helper,
    employerCta: pc.proFirmy.cta_primary,
    employerSecondary: pc.cenik.nav_cenik ?? "Ceník",
  },
  listings: {
    metaTitle: pc.nabidky.meta_title,
    claim: pc.nabidky.claim,
    helper: pc.nabidky.helper,
    ctaShowFilters: pc.filters.cta_show_filters,
    ctaFiltersShort: pc.filters.cta_filters_short,
    ctaApplyFilters: pc.filters.cta_apply_filters,
    ctaClearFilters: pc.filters.cta_clear_filters,
    drawerTitle: pc.filters.drawer_title,
    drawerHelper: "Nejdřív výpis. Drawer jen na filtry, které potřebujete.",
    filtersSalary: pc.filters.filters_salary,
    filtersProfession: "Obor",
    filtersMode: pc.filters.filters_mode,
    modeOnsite: pc.filters.filter_mode_onsite,
    modeHybrid: pc.filters.filter_mode_hybrid,
    modeRemote: pc.filters.filter_mode_remote,
    emptyTitle: pc.nabidky.empty_no_results_title,
    emptyBody: pc.nabidky.empty_no_results_body,
    hintRemote: pc.filters.filter_mode_remote,
  },
  job: {
    ctaApply: pc.detail.cta_apply,
    ctaBack: pc.detail.cta_back,
    ctaSave: pc.detail.cta_save,
    sectionAbout: pc.detail.section_about,
    sectionRequirements: pc.detail.section_requirements,
    sectionOffer: pc.detail.section_offer,
    sectionCompany: pc.detail.section_company,
    sectionRelated: "Podobné nabídky",
    labelSalary: pc.detail.label_salary,
    labelPlace: pc.detail.label_place,
    labelContract: pc.detail.label_contract,
    labelMode: pc.detail.label_mode,
    labelPublished: pc.detail.label_published,
    badgeFeatured: pc.jobCard.badge_featured,
    salaryNegotiable: pc.detail.salary_negotiable,
    helperNoAccount: pc.detail.helper_no_account,
    applyClaim: pc.detail.apply_claim,
    applyHelper: (company: string) => pc.detail.apply_helper.replace("{company}", company),
    labelName: pc.detail.label_name,
    labelPhone: pc.detail.label_phone,
    labelEmail: pc.detail.label_email,
    labelCv: pc.detail.label_cv,
    labelNote: pc.detail.label_note,
    placeholderNote: pc.detail.placeholder_note,
    ctaSubmit: pc.detail.cta_submit,
    consentGdpr: pc.detail.consent_gdpr,
    successTitle: pc.detail.success_title,
    successBody: (company: string) => pc.detail.success_body.replace("{company}", company),
    softTitle: pc.softSave.soft_title,
    softBody: pc.softSave.soft_body,
    softCta: pc.softSave.soft_cta,
    softDismiss: pc.softSave.soft_dismiss,
    emptyAbout: pc.detail.empty_about,
  },
  employers: {
    metaTitle: pc.proFirmy.meta_title,
    metaDescription: pc.proFirmy.meta_description,
    claim: pc.proFirmy.claim,
    helper: pc.proFirmy.helper,
    ctaPrimary: pc.proFirmy.cta_primary,
    ctaSecondary: pc.proFirmy.cta_secondary,
    ctaPost: pc.proFirmy.cta_post,
    sectionWhy: pc.proFirmy.section_why,
    why1Title: pc.proFirmy.why_1_title,
    why1Body: pc.proFirmy.why_1_body,
    why2Title: pc.proFirmy.why_2_title,
    why2Body: pc.proFirmy.why_2_body,
    why3Title: pc.proFirmy.why_3_title,
    why3Body: pc.proFirmy.why_3_body,
    sectionHow: pc.proFirmy.section_how,
    how1: pc.proFirmy.how_1,
    how2: pc.proFirmy.how_2,
    how3: pc.proFirmy.how_3,
    bottomHelper: pc.proFirmy.bottom_helper,
    linkCenik: pc.proFirmy.link_cenik,
    pricingSection: pc.proFirmy.pricing_section,
    pricingClaim: pc.proFirmy.pricing_claim,
    pricingHelper: pc.proFirmy.pricing_helper,
    pricingNote: pc.proFirmy.pricing_note,
    pricingCta: pc.proFirmy.pricing_cta,
  },
  cenik: {
    metaTitle: pc.cenik.meta_title,
    metaDescription: pc.cenik.meta_description,
    claim: pc.cenik.claim,
    helper: pc.cenik.helper,
  },
  authFirma: {
    loginClaim: pc.firmaLogin.claim,
    loginHelper: pc.firmaLogin.helper,
    loginLabelEmail: pc.firmaLogin.label_email,
    loginPlaceholder: pc.firmaLogin.placeholder_email,
    loginCta: pc.firmaLogin.cta_primary,
    loginSecondaryQ: pc.firmaLogin.secondary_q,
    loginSecondaryCta: pc.firmaLogin.secondary_cta,
    regClaim: pc.firmaRegister.claim,
    regHelper: pc.firmaRegister.helper,
    regLabelCompany: pc.firmaRegister.label_company,
    regLabelIco: pc.firmaRegister.label_ico,
    regLabelCity: pc.firmaRegister.label_city,
    regLabelName: pc.firmaRegister.label_first_name,
    regLabelEmail: pc.firmaRegister.label_email,
    regHelperAres: pc.firmaRegister.helper_ares,
    regCta: pc.firmaRegister.cta_primary,
    regSecondaryQ: pc.firmaRegister.secondary_q,
    regSecondaryCta: pc.firmaRegister.secondary_cta,
  },
  authSeeker: {
    claim: pc.ucetLogin.claim,
    helper: pc.ucetLogin.helper,
    cta: pc.ucetLogin.cta_primary,
    after: pc.ucetLogin.helper_after_send,
    linkEmployer: pc.ucetLogin.link_employer_login,
    softHint: "Účet je volitelný. Na nabídku můžete odpovědět i bez něj.",
  },
} as const;

export { pc as publicCopy, publicBrand };
