/** Anti-slop UI copy (PR18 drop-in, FairJobs brand). No em/en dash. */

import { BRAND } from "./brand";

export const copy = {
  home: {
    metaTitle: `${BRAND} · nabídky práce`,
    metaDescription: "Nabídky práce v Česku od ověřených firem. Hledejte podle pozice, místa a mzdy.",
    claim: "Práce v Česku. Od firem.",
    helper: "Pozice, místo a mzda na jednom místě. Všechny obory.",
    labelQuery: "Pozice nebo klíčové slovo",
    labelPlace: "Místo",
    placeholderQuery: "např. účetní, řidič, vývojář",
    placeholderPlace: "např. Praha, Brno",
    ctaSearch: "Hledat",
    ctaEmployers: "Pro firmy",
    sectionLatest: "Aktuální nabídky",
    fact1Title: "Mzda na první pohled",
    fact1Body: "Každá nabídka ukazuje odměnu, nebo upřímné Neuvedeno.",
    fact2Title: "Firma přes IČO",
    fact2Body: "Údaje z registru. Víte, kdo inzeruje.",
    fact3Title: "Jedno hledání",
    fact3Body: "Klíčové slovo a lokalita. Filtry v draweru, ne polovina obrazovky.",
    hubPoradna: "Poradna",
    hubPoradnaBody: "Jak vyjednat mzdu, změnit obor, nebo se připravit na pohovor.",
    hubKurzy: "Kurzy",
    hubKurzyBody: "Rekvalifikace a kurzy podle oboru. Online i prezenční.",
    hubNastroje: "Nástroje",
    hubNastrojeBody: "Čistá mzda, srovnání platů, checklist pohovoru. Bez účtu.",
    employerTitle: "Inzerce pro firmy",
    employerBody: "Uchazeči vidí mzdu, místo a úvazek. Odpovědi jdou přímo vám.",
    employerCta: "Založit účet firmy",
    employerSecondary: "Ceník",
  },
  listings: {
    metaTitle: `Nabídky práce · ${BRAND}`,
    claim: "Všechny nabídky",
    helper: "Filtrujte podle místa, mzdy, úvazku a režimu.",
    ctaShowFilters: "Upravit filtry",
    ctaFiltersShort: "Filtry",
    ctaApplyFilters: "Zobrazit nabídky",
    ctaClearFilters: "Zrušit filtry",
    drawerTitle: "Filtry",
    drawerHelper: "Listing first. Drawer jen na to, co potřebujete.",
    filtersSalary: "Mzda od",
    filtersProfession: "Obor",
    filtersMode: "Režim",
    modeOnsite: "Na místě",
    modeHybrid: "Hybrid",
    modeRemote: "Na dálku",
    emptyTitle: "Žádné nabídky pro tyto filtry",
    emptyBody: "Rozšiřte filtry, nebo je zrušte.",
    hintRemote: "Na dálku",
  },
  job: {
    ctaApply: "Odpovědět na nabídku",
    ctaBack: "Zpět na nabídky",
    ctaSave: "Uložit do oblíbených",
    sectionAbout: "O pozici",
    sectionRequirements: "Požadavky",
    sectionOffer: "Co nabízíme",
    sectionCompany: "O firmě",
    sectionRelated: "Podobné nabídky",
    labelSalary: "Mzda",
    labelPlace: "Místo",
    labelContract: "Úvazek",
    labelMode: "Režim",
    labelPublished: "Zveřejněno",
    badgeFeatured: "Priorita ve výpisu",
    salaryNegotiable: "mzda dohodou",
    helperNoAccount: "Bez účtu. Stačí jméno a telefon.",
    applyClaim: "Odpovědět na nabídku",
    applyHelper: (company: string) => `Odešlete přímo firmě ${company}.`,
    labelName: "Jméno a příjmení",
    labelPhone: "Telefon",
    labelEmail: "E-mail (nepovinné)",
    labelCv: "Životopis (nepovinné)",
    labelNote: "Zpráva firmě (nepovinné)",
    placeholderNote: "Krátce k zkušenosti nebo dostupnosti",
    ctaSubmit: "Odeslat firmě",
    consentGdpr: "Souhlasím se zpracováním údajů za účelem kontaktování k této nabídce.",
    successTitle: "Odpověď je odeslaná",
    successBody: (company: string) => `Firma ${company} se vám ozve.`,
    softTitle: "Uložte si účet",
    softBody: "Odpověď je u firmy. Založte účet a mějte oblíbené nabídky na jednom místě.",
    softCta: "Založit účet",
    softDismiss: "Teď ne",
    emptyAbout: "Popis pozice doplní firma.",
  },
  employers: {
    metaTitle: `Pro firmy · ${BRAND}`,
    metaDescription: `Inzerujte práci na ${BRAND}. Jasná mzda v inzerátu, odpovědi uchazečů rovnou vám.`,
    claim: "Inzerce pro firmy",
    helper: "Uchazeči vidí mzdu, místo a úvazek. Odpovědi jdou přímo vám.",
    ctaPrimary: "Založit účet firmy",
    ctaSecondary: "Přihlásit se",
    ctaPost: "Vystavit nabídku",
    sectionWhy: `Proč ${BRAND}`,
    why1Title: "Inzerát, kterému se věří",
    why1Body: "Mzda, místo a úvazek hned na kartě. Méně slepých odpovědí, víc relevantních lidí.",
    why2Title: "Schránka odpovědí",
    why2Body: "Jméno, telefon, e-mail a životopis u každé žádosti. Nic se neztrácí v e-mailech.",
    why3Title: "Firma ověřená přes IČO",
    why3Body: "Údaje z ARES. Uchazeči ví, že inzeruje reálná firma.",
    sectionHow: "Jak to funguje",
    how1: "Založíte účet firmy odkazem z e-mailu.",
    how2: "Vystavíte nabídku s jasnou mzdou a místem.",
    how3: "Odpovědi čtete ve schránce a ozvete se uchazeči.",
    bottomHelper: "Účet firmy za minuty. První nabídka hned potom.",
    linkCenik: "Kompletní ceník",
    pricingSection: "Ceník",
    pricingClaim: "Ceník inzerce",
    pricingHelper: "Ceny bez DPH. Platba po registraci účtu.",
    pricingNote: `Ceny jsou orientační. Platbu na ${BRAND} domluvíte po registraci.`,
    pricingCta: "Založit účet firmy",
  },
  cenik: {
    metaTitle: `Ceník · ${BRAND}`,
    metaDescription: `Ceny inzerce na ${BRAND}. Start, Standard a Plus. Bez DPH.`,
    claim: "Ceník inzerce",
    helper: "Vyberte balíček podle počtu aktivních nabídek. Ceny bez DPH.",
  },
  authFirma: {
    loginClaim: "Přihlášení firmy",
    loginHelper: "Na pracovní e-mail pošleme odkaz. Heslo nepoužíváme.",
    loginLabelEmail: "Pracovní e-mail",
    loginPlaceholder: "jmeno@firma.cz",
    loginCta: "Poslat přihlašovací odkaz",
    loginSecondaryQ: "Nemáte účet?",
    loginSecondaryCta: "Zaregistrujte firmu",
    regClaim: "Registrace firmy",
    regHelper: "Doplňte firmu a kontakt. Přihlašovací odkaz přijde na e-mail.",
    regLabelCompany: "Název firmy",
    regLabelIco: "IČO",
    regLabelCity: "Město",
    regLabelName: "Jméno",
    regLabelEmail: "Pracovní e-mail",
    regHelperAres: "Údaje firmy doplníme z ARES podle IČO.",
    regCta: "Založit účet a poslat odkaz",
    regSecondaryQ: "Už máte účet?",
    regSecondaryCta: "Přihlaste se",
  },
  authSeeker: {
    claim: "Přihlášení",
    helper: "Na e-mail pošleme odkaz. Heslo nepoužíváme.",
    cta: "Poslat přihlašovací odkaz",
    after: "Odkaz jsme poslali. Podívejte se do schránky i do spamu.",
    linkEmployer: "Jste firma? Přihlášení firem",
    softHint: "Účet je volitelný. Na nabídku můžete odpovědět i bez něj.",
  },
} as const;
