/** Czech UI copy from docs/copy/COPY-PACK.md. No em dash or en dash. */

export const copy = {
  brand: "DílnaJobs",
  claim: "Práce v Česku. Od firem.",
  footer: "© 2026 DílnaJobs · nabídky práce",
  nav: {
    nabidky: "Nabídky",
    proFirmy: "Pro firmy",
    login: "Přihlášení firem",
    register: "Registrace firmy",
    ariaMain: "Hlavní",
    ariaMenu: "Menu",
  },
  home: {
    metaTitle: "DílnaJobs · nabídky práce",
    metaDescription: "Nabídky práce v Česku. Hledejte podle pozice, místa a mzdy. Odpovězte přímo firmě.",
    helper: "Všechny obory. Filtrujte podle pozice, místa a mzdy.",
    labelQuery: "Pozice nebo klíčové slovo",
    labelPlace: "Místo",
    placeholderQuery: "např. účetní, řidič, vývojář",
    placeholderPlace: "např. Praha, Brno",
    ctaSearch: "Hledat",
    ctaEmployers: "Pro firmy",
    sectionLatest: "Aktuální nabídky",
  },
  nabidky: {
    metaTitle: "Nabídky práce · DílnaJobs",
    metaDescription: "Procházejte nabídky práce. Filtrujte podle pozice, místa, úvazku a mzdy.",
    claim: "Všechny nabídky",
    helper: "Upravte filtry podle pozice, místa a mzdy.",
    labelQuery: "Pozice nebo klíčové slovo",
    labelPlace: "Místo",
    ctaSearch: "Hledat",
    ctaShowFilters: "Zobrazit filtry",
    sectionResults: "Výsledky",
    filtersPlace: "Místo",
    filtersCategory: "Obor",
    filtersContract: "Úvazek",
    filtersSalary: "Mzda od",
    filtersSeniority: "Seniorita",
    emptyNoResultsTitle: "Žádné nabídky pro tyto filtry",
    emptyNoResultsBody: "Upravte pozici, místo nebo mzdu a zkuste to znovu.",
    emptyNoResultsCta: "Zrušit filtry",
    emptyNoQueryTitle: "Zadejte pozici nebo místo",
    emptyNoQueryBody: "Například účetní v Brně, nebo řidič Praha.",
    emptyErrorTitle: "Nabídky se nepodařilo načíst",
    emptyErrorBody: "Zkuste to znovu. Když problém zůstane, napište nám.",
    emptyErrorCta: "Zkusit znovu",
  },
  card: {
    labelSalary: "Mzda",
    labelPlace: "Místo",
    labelContract: "Úvazek",
    labelSeniority: "Seniorita",
    labelPublished: "Zveřejněno",
    badgeNew: "Nové",
    badgeFeatured: "Zvýrazněné",
    badgeVerified: "Ověřená firma",
    badgePending: "Ověření probíhá",
    ctaOpen: "Zobrazit nabídku",
  },
  detail: {
    ctaApply: "Odpovědět na nabídku",
    sectionAbout: "O pozici",
    sectionRequirements: "Požadavky",
    sectionOffer: "Co nabízíme",
    sectionCompany: "O firmě",
    applyClaim: "Odpovědět na nabídku",
    applyHelper: (company: string) => `Údaje uvidí jen ${company}.`,
    labelName: "Jméno a příjmení",
    labelPhone: "Telefon",
    labelEmail: "E-mail (nepovinné)",
    labelCv: "Životopis (nepovinné)",
    labelNote: "Zpráva firmě (nepovinné)",
    ctaSubmit: "Odeslat firmě",
    successTitle: "Odpověď je odeslaná",
    successBody: "Ozvou se vám z firmy.",
    errorRequired: "Doplňte povinná pole.",
    errorPhone: "Zkontrolujte telefonní číslo.",
  },
  employers: {
    metaTitle: "Pro firmy · DílnaJobs",
    metaDescription: "Inzerujte nabídky práce na DílnaJobs. Odpovědi od uchazečů na jednom místě.",
    claim: "Inzerce nabídek práce",
    helper: "Zveřejněte pozici. Uchazeči odpoví přímo vám.",
    ctaPrimary: "Založit účet firmy",
    ctaSecondary: "Přihlásit se",
    ctaPost: "Vystavit nabídku",
    sectionWhy: "Proč DílnaJobs",
    why1Title: "Jasný inzerát",
    why1Body: "Mzda, místo a úvazek hned vidět. Méně zbytečných odpovědí.",
    why2Title: "Odpovědi na jednom místě",
    why2Body: "Telefon, e-mail a životopis u každé žádosti.",
    why3Title: "Rychlé spuštění",
    why3Body: "Účet firmy a první nabídka během pár minut.",
    bottomHelper: "Založte účet firmy a zveřejněte první nabídku.",
  },
  login: {
    metaTitle: "Přihlášení firmy · DílnaJobs",
    metaDescription: "Přihlaste se k účtu firmy odkazem z e-mailu.",
    claim: "Přihlášení firmy",
    helper: "Na e-mail pošleme odkaz pro přihlášení.",
    labelEmail: "Pracovní e-mail",
    placeholderEmail: "jmeno@firma.cz",
    ctaPrimary: "Poslat přihlašovací odkaz",
    helperAfterSend: "Odkaz jsme poslali. Podívejte se do schránky.",
    helperSecondary: "Nemáte účet?",
    ctaSecondary: "Zaregistrujte firmu",
    previewNote: "Náhled. Odkaz zatím neodesíláme.",
  },
  register: {
    metaTitle: "Registrace firmy · DílnaJobs",
    metaDescription: "Založte účet firmy. Přihlašovací odkaz přijde na e-mail.",
    claim: "Registrace firmy",
    helper: "Doplňte firmu a kontakt. Přihlašovací odkaz přijde na e-mail.",
    labelCompany: "Název firmy",
    labelIco: "IČO",
    labelDic: "DIČ (nepovinné)",
    labelCity: "Město",
    labelFirstName: "Jméno",
    labelLastName: "Příjmení",
    labelEmail: "Pracovní e-mail",
    helperAres: "Údaje firmy doplníme z ARES podle IČO.",
    placeholderCompany: "např. Acme s.r.o.",
    placeholderIco: "12345678",
    placeholderCity: "Praha",
    placeholderEmail: "personalista@firma.cz",
    ctaPrimary: "Založit účet a poslat odkaz",
    helperAfterSend: "Účet je založený. Odkaz pro přihlášení jsme poslali na e-mail.",
    helperSecondary: "Už máte účet?",
    ctaSecondary: "Přihlaste se",
    previewNote: "Náhled. Účet ani odkaz zatím neodesíláme.",
  },
} as const;

export function salaryRange(from: number, to: number): string {
  const fmt = (n: number) => new Intl.NumberFormat("cs-CZ").format(n);
  return `${fmt(from)} až ${fmt(to)} Kč`;
}

export function salaryFrom(from: number): string {
  return `od ${new Intl.NumberFormat("cs-CZ").format(from)} Kč`;
}
