export const copyPart3 = {
  ucetOblibene: {
    aria_save: 'Uložit do oblíbených',
    aria_saved: 'V oblíbených',
    claim: 'Oblíbené',
    cta_browse: 'Procházet nabídky',
    cta_remove: 'Odebrat',
    empty_body: 'Uložte si nabídku ikonou srdce.',
    empty_title: 'Zatím žádné oblíbené',
    helper: 'Nabídky, které si chcete nechat.',
    meta_description: 'Uložené nabídky práce.',
    meta_title: 'Oblíbené · FairJobs',
  },
  softSave: {
    soft_body: 'Odpověď je u firmy. Založte účet a mějte oblíbené nabídky na jednom místě.',
    soft_cta: 'Založit účet',
    soft_dismiss: 'Teď ne',
    soft_title: 'Uložte si účet',
  },
  magicMail: {
    body_login: 'Klikněte na odkaz a přihlásíte se. Odkaz platí omezenou dobu.',
    body_register: 'Účet je připravený. Klikněte na odkaz a pokračujte.',
    cta_button: 'Přihlásit se',
    footer_mail: 'FairJobs · nabídky práce v Česku',
    greeting: 'Dobrý den,',
    ignore: 'Pokud jste o odkaz nežádali, e-mail ignorujte.',
    subject_login: 'Přihlášení na FairJobs',
    subject_register: 'Váš účet na FairJobs',
  },
  chrome: {
    aria_main: 'Hlavní',
    aria_menu: 'Menu',
    brand: 'FairJobs',
    nav_account: 'Můj účet',
    nav_cv: 'Vytvořit životopis',
    nav_favorites: 'Oblíbené',
    nav_kurzy: 'Kurzy',
    nav_login: 'Přihlášení firem',
    nav_login_seeker: 'Přihlásit se',
    nav_nabidky: 'Nabídky',
    nav_nastroje: 'Nástroje',
    nav_poradna: 'Poradna',
    nav_pro_firmy: 'Pro firmy',
    nav_pruvodce: 'Průvodce',
    nav_register: 'Registrace firmy',
    path_cv: '/zivotopis',
  },
  chromeSeeker: {
    nav_account: 'Můj účet',
    nav_favorites: 'Oblíbené',
    nav_login_seeker: 'Přihlásit se',
    path_favorites: '/ucet/oblibene',
    path_login: '/ucet/prihlaseni',
    path_profile: '/ucet/profil',
    path_register: '/ucet/registrace',
  },
} as const;
