/** FairJobs public UI copy. SoT: docs/copy/COPY-PACK.md v1.12 + PR18 drop-in.
 *  Copy-owned. Engineer: import and replace hardcoded Czech strings.
 *  Hard ban: no U+2014 / U+2013 in any value.
 *  Do not invent strings; ask Copy.
 */

export const brand = {
  name: 'FairJobs',
  domain: 'fairjobs.cz',
  sep: '·',
} as const;

export const copy = {
  home: {
    claim: 'Práce v Česku. Od firem.',
    cta_employers: 'Pro firmy',
    cta_search: 'Hledat',
    footer: '© 2026 FairJobs · nabídky práce',
    helper: 'Pozice, místo a mzda na jednom místě. Všechny obory.',
    label_place: 'Místo',
    label_query: 'Pozice nebo klíčové slovo',
    meta_description: 'Nabídky práce v Česku od ověřených firem. Hledejte podle pozice, místa a mzdy.',
    meta_title: 'FairJobs · nabídky práce',
    nav_login: 'Přihlášení firem',
    nav_nabidky: 'Nabídky',
    nav_pro_firmy: 'Pro firmy',
    placeholder_place: 'např. Praha, Brno',
    placeholder_query: 'např. účetní, řidič, vývojář',
    section_latest: 'Aktuální nabídky',
  },
  nabidky: {
    aria_active_filters: 'Aktivní filtry',
    aria_close_filters: 'Zavřít filtry',
    aria_remove_filter: 'Odebrat filtr',
    claim: 'Všechny nabídky',
    cta_all_jobs: 'Zobrazit všechny nabídky',
    cta_apply_filters: 'Zobrazit nabídky',
    cta_clear_filters: 'Zrušit filtry',
    cta_filters_short: 'Filtry',
    cta_search: 'Hledat',
    cta_show_filters: 'Upravit filtry',
    drawer_title: 'Filtry',
    empty_error_body: 'Zkuste to znovu. Když problém zůstane, napište nám.',
    empty_error_cta: 'Zkusit znovu',
    empty_error_title: 'Nabídky se nepodařilo načíst',
    empty_no_query_body: 'Například účetní Brno, řidič Praha.',
    empty_no_query_title: 'Zadejte pozici nebo místo',
    empty_no_results_body: 'Rozšiřte filtry, nebo je zrušte.',
    empty_no_results_cta: 'Zrušit filtry',
    empty_no_results_title: 'Žádné nabídky pro tyto filtry',
    filter_mode_all: 'Vše',
    filter_mode_hybrid: 'Hybrid',
    filter_mode_onsite: 'Na místě',
    filter_mode_remote: 'Na dálku',
    filters_contract: 'Úvazek',
    filters_mode: 'Režim',
    filters_place: 'Místo',
    filters_salary: 'Mzda od',
    filters_seniority: 'Seniorita',
    footer: '© 2026 FairJobs · nabídky práce',
    helper: 'Filtrujte podle místa, mzdy, úvazku a režimu.',
    label_place: 'Místo',
    label_query: 'Pozice nebo klíčové slovo',
    meta_description: 'Procházejte nabídky práce. Filtrujte podle pozice, místa, úvazku a mzdy.',
    meta_title: 'Nabídky práce · FairJobs',
    results_count: '{n} výsledků',
    section_fields: 'Všechny obory',
    section_results: 'Výsledky',
  },
  filters: {
    cta_apply_filters: 'Zobrazit nabídky',
    cta_clear_filters: 'Zrušit filtry',
    cta_filters_short: 'Filtry',
    cta_show_filters: 'Upravit filtry',
    drawer_title: 'Filtry',
    filter_mode_all: 'Vše',
    filter_mode_hybrid: 'Hybrid',
    filter_mode_onsite: 'Na místě',
    filter_mode_remote: 'Na dálku',
    filters_contract: 'Úvazek',
    filters_mode: 'Režim',
    filters_place: 'Místo',
    filters_salary: 'Mzda od',
    filters_seniority: 'Seniorita',
  },
  jobCard: {
    badge_featured: 'Zvýrazněné',
    badge_new: 'Nové',
    badge_verified: 'Ověřeno',
    contract_dpc: 'DPČ',
    contract_dpp: 'DPP',
    contract_hpp: 'HPP',
    contract_ico: 'IČO / živnost',
    cta_open: 'Zobrazit nabídku',
    label_contract: 'Úvazek',
    label_field: 'Obor',
    label_place: 'Místo',
    label_published: 'Zveřejněno',
    label_salary: 'Mzda',
    label_seniority: 'Seniorita',
    meta_company: '{company}',
    published_days_ago: 'Zveřejněno před {n} dny',
    published_today: 'Zveřejněno dnes',
    published_yesterday: 'Zveřejněno včera',
    salary_from: 'od {from} Kč',
    salary_negotiable: 'mzda dohodou',
    salary_range: '{from} až {to} Kč',
    work_mode_hybrid: 'Hybrid',
    work_mode_label: 'Režim',
    work_mode_onsite: 'Na místě',
    work_mode_remote: 'Na dálku',
  },
  detail: {
    apply_claim: 'Odpovědět na nabídku',
    apply_helper: 'Odešlete přímo firmě {company}.',
    badge_verified: 'Ověřeno',
    consent_gdpr: 'Souhlasím se zpracováním údajů za účelem kontaktování k této nabídce.',
    cta_apply: 'Odpovědět na nabídku',
    cta_back: 'Zpět na nabídky',
    cta_save: 'Uložit do oblíbených',
    cta_saved: 'V oblíbených',
    cta_submit: 'Odeslat firmě',
    empty_about: 'Popis pozice doplní firma.',
    error_phone: 'Zkontrolujte telefonní číslo.',
    error_required: 'Doplňte povinná pole.',
    helper_no_account: 'Bez účtu. Stačí jméno a telefon.',
    label_contract: 'Úvazek',
    label_cv: 'Životopis (nepovinné)',
    label_email: 'E-mail (nepovinné)',
    label_mode: 'Režim',
    label_name: 'Jméno a příjmení',
    label_note: 'Zpráva firmě (nepovinné)',
    label_phone: 'Telefon',
    label_place: 'Místo',
    label_published: 'Zveřejněno',
    label_salary: 'Mzda',
    label_seniority: 'Seniorita',
    meta_title_pattern: '{title} · {company} · FairJobs',
    placeholder_note: 'Krátce k zkušenosti nebo dostupnosti',
    preview_note: 'Náhled. Odpověď zatím neodesíláme.',
    salary_negotiable: 'mzda dohodou',
    section_about: 'O pozici',
    section_apply: 'Odpovědět',
    section_company: 'O firmě',
    section_offer: 'Co nabízíme',
    section_requirements: 'Požadavky',
    share_label: 'Sdílet nabídku',
    soft_body: 'Odpověď je u firmy. Založte účet a mějte oblíbené nabídky na jednom místě.',
    soft_cta: 'Založit účet',
    soft_dismiss: 'Teď ne',
    soft_title: 'Uložte si účet',
    success_body: 'Firma {company} se vám ozve.',
    success_title: 'Odpověď je odeslaná',
  },
  PLACEHOLDER_REST: true,
} as const;
