export const copyPart2 = {
  cenik: {
    cenik_claim: 'Ceník inzerce',
    cenik_helper: 'Vyberte balíček podle počtu aktivních nabídek. Ceny bez DPH.',
    cenik_meta_description: 'Ceny inzerce na FairJobs. Start, Standard a Plus. Bez DPH.',
    cenik_meta_title: 'Ceník · FairJobs',
    claim: 'Ceník inzerce',
    cta_primary: 'Založit účet firmy',
    helper: 'Vyberte balíček podle počtu aktivních nabídek. Ceny bez DPH.',
    meta_description: 'Ceny inzerce na FairJobs. Start, Standard a Plus. Bez DPH.',
    meta_title: 'Ceník · FairJobs',
    nav_cenik: 'Ceník',
    plan_plus_f1: 'Až 15 aktivních nabídek',
    plan_plus_f2: 'Priorita ve výpisu a logo firmy',
    plan_plus_f3: 'Prioritní podpora',
    plan_plus_name: 'Plus',
    plan_plus_period: '/ 30 dní',
    plan_plus_price: '8 990 Kč',
    plan_standard_f1: 'Až 5 aktivních nabídek',
    plan_standard_f2: 'Zvýraznění ve výsledcích',
    plan_standard_f3: 'Schránka odpovědí a životopisy',
    plan_standard_name: 'Standard',
    plan_standard_period: '/ 30 dní',
    plan_standard_price: '4 990 Kč',
    plan_start_f1: '1 aktivní nabídka',
    plan_start_f2: 'Schránka odpovědí',
    plan_start_f3: 'Ověření firmy přes IČO',
    plan_start_name: 'Start',
    plan_start_period: '/ 30 dní',
    plan_start_price: '2 490 Kč',
    pricing_claim: 'Ceník inzerce',
    pricing_cta: 'Založit účet firmy',
    pricing_helper: 'Ceny bez DPH. Platba po registraci účtu.',
    pricing_note: 'Ceny jsou orientační. Platbu domluvíte po registraci.',
    pricing_section: 'Ceník',
  },
  firmaLogin: {
    after: 'Odkaz jsme poslali. Podívejte se do schránky i do spamu.',
    claim: 'Přihlášení firmy',
    cta: 'Poslat přihlašovací odkaz',
    cta_primary: 'Poslat přihlašovací odkaz',
    cta_secondary: 'Zaregistrujte firmu',
    footer: '© 2026 FairJobs · nabídky práce',
    helper: 'Na pracovní e-mail pošleme odkaz. Heslo nepoužíváme.',
    helper_after_send: 'Odkaz jsme poslali. Podívejte se do schránky i do spamu.',
    helper_secondary: 'Nemáte účet?',
    label_email: 'Pracovní e-mail',
    meta_description: 'Přihlaste se k účtu firmy odkazem z e-mailu.',
    meta_title: 'Přihlášení firmy · FairJobs',
    placeholder: 'jmeno@firma.cz',
    placeholder_email: 'jmeno@firma.cz',
    preview_note: 'Náhled. Odkaz zatím neodesíláme.',
    secondary_cta: 'Zaregistrujte firmu',
    secondary_q: 'Nemáte účet?',
  },
  firmaRegister: {
    after: 'Účet je založený. Odkaz pro přihlášení jsme poslali na e-mail.',
    claim: 'Registrace firmy',
    cta: 'Založit účet a poslat odkaz',
    cta_primary: 'Založit účet a poslat odkaz',
    cta_secondary: 'Přihlaste se',
    footer: '© 2026 FairJobs · nabídky práce',
    helper: 'Doplňte firmu a kontakt. Přihlašovací odkaz přijde na e-mail.',
    helper_after_send: 'Účet je založený. Odkaz pro přihlášení jsme poslali na e-mail.',
    helper_ares: 'Údaje firmy doplníme z ARES podle IČO.',
    helper_secondary: 'Už máte účet?',
    label_city: 'Město',
    label_company: 'Název firmy',
    label_dic: 'DIČ (nepovinné)',
    label_email: 'Pracovní e-mail',
    label_first: 'Jméno',
    label_first_name: 'Jméno',
    label_ico: 'IČO',
    label_last: 'Příjmení',
    label_last_name: 'Příjmení',
    meta_description: 'Založte účet firmy. Přihlašovací odkaz přijde na e-mail.',
    meta_title: 'Registrace firmy · FairJobs',
    placeholder_city: 'Praha',
    placeholder_company: 'např. Acme s.r.o.',
    placeholder_email: 'personalista@firma.cz',
    placeholder_ico: '12345678',
    preview_note: 'Náhled. Účet ani odkaz zatím neodesíláme.',
    secondary_cta: 'Přihlaste se',
    secondary_q: 'Už máte účet?',
  },
  ucetLogin: {
    after: 'Odkaz jsme poslali. Podívejte se do schránky i do spamu.',
    claim: 'Přihlášení',
    cta: 'Poslat přihlašovací odkaz',
    cta_primary: 'Poslat přihlašovací odkaz',
    cta_secondary: 'Zaregistrujte se',
    footer: '© 2026 FairJobs · nabídky práce',
    helper: 'Na e-mail pošleme odkaz. Heslo nepoužíváme.',
    helper_after_send: 'Odkaz jsme poslali. Podívejte se do schránky i do spamu.',
    helper_secondary: 'Nemáte účet?',
    label_email: 'E-mail',
    link_employer: 'Jste firma? Přihlášení firem',
    link_employer_login: 'Jste firma? Přihlášení firem',
    link_employer_reg: 'Jste firma? Registrace firmy',
    meta_description: 'Přihlaste se k účtu odkazem z e-mailu.',
    meta_title: 'Přihlášení · FairJobs',
    placeholder_email: 'vas@email.cz',
  },
  ucetRegister: {
    after: 'Účet je založený. Odkaz pro přihlášení jsme poslali na e-mail.',
    claim: 'Registrace',
    cta: 'Založit účet a poslat odkaz',
    cta_primary: 'Založit účet a poslat odkaz',
    cta_secondary: 'Přihlaste se',
    footer: '© 2026 FairJobs · nabídky práce',
    helper: 'Založte účet odkazem z e-mailu. Oblíbené a odpovědi na jednom místě.',
    helper_after_send: 'Účet je založený. Odkaz pro přihlášení jsme poslali na e-mail.',
    helper_secondary: 'Už máte účet?',
    label_email: 'E-mail',
    label_first_name: 'Jméno',
    label_last_name: 'Příjmení',
    link_employer: 'Jste firma? Registrace firmy',
    meta_description: 'Založte účet. Přihlašovací odkaz přijde na e-mail.',
    meta_title: 'Registrace · FairJobs',
    placeholder_email: 'vas@email.cz',
  },
  ucetProfil: {
    claim: 'Můj účet',
    cta_logout: 'Odhlásit se',
    cta_save: 'Uložit',
    empty_name: 'Doplňte jméno',
    helper: 'Kontakt a základní údaje.',
    helper_saved: 'Uloženo.',
    label_email: 'E-mail',
    label_first_name: 'Jméno',
    label_last_name: 'Příjmení',
    label_phone: 'Telefon (nepovinné)',
    meta_description: 'Nastavení účtu a kontaktních údajů.',
    meta_title: 'Můj účet · FairJobs',
  },
} as const;
