#!/usr/bin/env node
/**
 * Embed locked Design SoT CSS into src/app/sot.css as a monolith.
 * Tailwind v4 drops nested `@import url(...)`; writing the full rules
 * into sot.css (imported from globals.css) is the reliable path.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const aPath = join(root, "enterprise-mvp/preview-v6-soa/styles-a.css");
const bPath = join(root, "enterprise-mvp/preview-v6-soa/styles-b.css");
const outPath = join(root, "src/app/sot.css");

let a = readFileSync(aPath, "utf8");
let b = readFileSync(bPath, "utf8");

// Prefer next/font Inter variable over Google Fonts @import in the locked pack.
a = a.replace(
  /@import url\("https:\/\/fonts\.googleapis\.com\/css2\?family=Inter:[^"]+"\);\s*/g,
  "/* Inter via next/font --font-inter */\n",
);
a = a.replace(
  /--font:\s*Inter,/g,
  "--font: var(--font-inter), Inter,",
);

const banner =
  "/* AUTO-GENERATED by scripts/embed-sot-css.mjs — do not edit by hand.\n" +
  "   Source: enterprise-mvp/preview-v6-soa/styles-{a,b}.css */\n\n";

writeFileSync(outPath, banner + a + b);
console.log(`embed-sot-css: wrote ${outPath} (${banner.length + a.length + b.length} chars)`);
