#!/usr/bin/env node
/**
 * Embed locked Design SoT CSS into src/app/sot.css as a monolith.
 * Tailwind v4 drops nested `@import url(...)`; writing the full rules
 * into sot.css (imported from globals.css) is the reliable path.
 *
 * Prefer *.css.gz.b64 siblings when present (exact disk SoT without
 * oversized MCP text payloads). Fall back to plain *.css.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const aPath = join(root, "enterprise-mvp/preview-v6-soa/styles-a.css");
const bPath = join(root, "enterprise-mvp/preview-v6-soa/styles-b.css");
const aB64Path = join(root, "enterprise-mvp/preview-v6-soa/styles-a.css.gz.b64");
const bB64Path = join(root, "enterprise-mvp/preview-v6-soa/styles-b.css.gz.b64");
const outPath = join(root, "src/app/sot.css");

function loadCss(plainPath, b64Path) {
  if (existsSync(b64Path)) {
    const b64 = readFileSync(b64Path, "utf8").trim();
    return gunzipSync(Buffer.from(b64, "base64")).toString("utf8");
  }
  return readFileSync(plainPath, "utf8");
}

let a = loadCss(aPath, aB64Path);
let b = loadCss(bPath, bB64Path);

// Prefer next/font Inter variable over Google Fonts @import in the locked pack.
a = a.replace(
  /@import url\("https:\/\/fonts\.googleapis\.com\/css2\?family=Inter:[^"]+"\);\s*/g,
  "/* Inter via next/font --font-inter */\n",
);
a = a.replace(
  /--font:\s*Inter,/g,
  "--font: var(--font-inter), Inter,",
);

const banner =
  "/* AUTO-GENERATED by scripts/embed-sot-css.mjs — do not edit by hand.\n" +
  "   Source: enterprise-mvp/preview-v6-soa/styles-{a,b}.css[.gz.b64] */\n\n";

writeFileSync(outPath, banner + a + b);
console.log(`embed-sot-css: wrote ${outPath} (${banner.length + a.length + b.length} chars)`);
